#!/usr/bin/env python3
# Generate ICONS.INC : 16x16 line-art menu icons for PS2GUI.
# Each icon is 16 words; bit (0x8000>>c) set => dark-red art pixel at column c,
# clear => white tile.  Drawn black-on-white here, then black => set bit.
from PIL import Image, ImageDraw

S = 16
def new():
    im = Image.new("L", (S, S), 255)
    return im, ImageDraw.Draw(im)

icons = {}   # name -> image

# --- battery (Power & Battery / charging) ---
im, d = new()
d.rectangle([2, 5, 11, 11], outline=0)
d.rectangle([11, 7, 12, 9], fill=0)
d.line([4, 7, 4, 9], fill=0); d.line([6, 7, 6, 9], fill=0); d.line([8, 7, 8, 9], fill=0)
icons["batt"] = im

# --- monitor (Display) ---
im, d = new()
d.rectangle([2, 2, 13, 10], outline=0)
d.line([7, 11, 7, 12], fill=0); d.line([8, 11, 8, 12], fill=0)
d.line([4, 13, 11, 13], fill=0)
icons["disp"] = im

# --- plug (Devices) ---
im, d = new()
d.line([6, 1, 6, 4], fill=0); d.line([9, 1, 9, 4], fill=0)
d.rectangle([4, 4, 11, 9], outline=0)
d.line([7, 9, 7, 14], fill=0); d.line([8, 9, 8, 14], fill=0)
icons["dev"] = im

# --- keyboard (Keyboard & Pointer) ---
im, d = new()
d.rectangle([1, 5, 14, 11], outline=0)
for y in (7, 9):
    for x in (3, 5, 7, 9, 11):
        d.point((x, y), fill=0)
icons["kbd"] = im

# --- gear/cog (Advanced) ---
im, d = new()
d.ellipse([4, 4, 11, 11], outline=0)
d.line([7, 1, 8, 1], fill=0); d.line([7, 14, 8, 14], fill=0)
d.line([1, 7, 1, 8], fill=0); d.line([14, 7, 14, 8], fill=0)
d.line([3, 3, 4, 4], fill=0); d.line([11, 3, 12, 2], fill=0)
d.line([3, 12, 2, 13], fill=0); d.line([12, 12, 13, 13], fill=0)
icons["adv"] = im

# --- chip / ROM (Dumps & ROM) ---
im, d = new()
d.rectangle([4, 4, 11, 11], outline=0)
for x in (6, 8, 10):
    d.line([x, 1, x, 3], fill=0); d.line([x, 12, x, 14], fill=0)
for y in (6, 8, 10):
    d.line([1, y, 3, y], fill=0); d.line([12, y, 14, y], fill=0)
icons["chip"] = im

# --- clipboard + check (System Test) ---
im, d = new()
d.rectangle([3, 2, 12, 14], outline=0)
d.rectangle([6, 1, 9, 3], fill=0)
d.line([5, 9, 7, 11], fill=0); d.line([7, 11, 11, 6], fill=0)
icons["check"] = im

# --- magnifier (Diagnostics) ---
im, d = new()
d.ellipse([2, 2, 9, 9], outline=0)
d.line([9, 9, 14, 14], fill=0); d.line([8, 9, 13, 14], fill=0)
icons["mag"] = im

# --- floppy disk (Backup & Restore) ---
im, d = new()
d.rectangle([2, 2, 13, 13], outline=0)
d.rectangle([5, 2, 10, 5], fill=0)      # metal shutter
d.rectangle([5, 8, 11, 12], outline=0)  # label
icons["floppy"] = im

# --- info circle (Information) ---
im, d = new()
d.ellipse([2, 2, 13, 13], outline=0)
d.point((7, 5), fill=0); d.point((8, 5), fill=0)
d.line([7, 7, 7, 11], fill=0); d.line([8, 7, 8, 11], fill=0)
icons["info"] = im

# --- sliders (a setting: R_ITEM) ---
im, d = new()
for y in (4, 8, 12):
    d.line([2, y, 13, y], fill=0)
d.rectangle([9, 3, 11, 5], fill=0)
d.rectangle([4, 7, 6, 9], fill=0)
d.rectangle([10, 11, 12, 13], fill=0)
icons["set"] = im

# --- play/run triangle (an action: R_ACT) ---
im, d = new()
d.polygon([(4, 3), (4, 13), (13, 8)], outline=0)
icons["run"] = im

# emit
order = ["batt", "disp", "dev", "kbd", "adv", "chip", "check", "mag",
         "floppy", "info", "set", "run"]

def words(im):
    # keep art inside rows 2..13 so the row's selection box (cell edges) and the
    # 2px inter-tile gap never clip icon pixels.
    px = im.load()
    out = []
    for r in range(S):
        w = 0
        if 2 <= r <= 13:
            for c in range(S):
                if px[c, r] < 128:
                    w |= (1 << (15 - c))
        out.append(w)
    return out

lines = ["; ICONS.INC  -  auto-generated by tools/make_icons.py",
         "; 16x16 line-art menu icons (bit set = dark-red art, clear = white tile)",
         ""]
for name in order:
    w = words(icons[name])
    lines.append("ic_%s:" % name)
    for i in range(0, 16, 8):
        lines.append("        dw " + ", ".join("0x%04X" % x for x in w[i:i+8]))
lines.append("")
lines.append("; category -> icon (main-menu order, 10 categories)")
lines.append("catic:  dw ic_batt, ic_disp, ic_dev, ic_kbd, ic_adv, ic_chip, ic_check, ic_mag, ic_floppy, ic_info")
lines.append("")

open("/Users/ahmadbyagowi/git/PS2GUI/ICONS.INC", "w").write("\n".join(lines) + "\n")
print("wrote ICONS.INC,", len(order), "icons")
